import json
from pathlib import Path
from datetime import datetime, timezone
from uuid import uuid4

from tools.transactions import get_transaction_summary, get_failed_transactions
from tools.workflows import (
    start_workflow_run,
    complete_workflow_run,
    fail_workflow_run,
)


REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports"


def generate_report_id() -> str:
    """
    Generate a unique report ID.
    Example: REPORT-20260610-A8F32C
    """
    date_part = datetime.now(timezone.utc).strftime("%Y%m%d")
    random_part = uuid4().hex[:6].upper()
    return f"REPORT-{date_part}-{random_part}"


def generate_daily_ops_report(date: str, triggered_by_role: str = "admin"):
    """
    Generate a daily banking operations report for a given date.

    The report includes:
    - transaction summary
    - failed transactions
    - failed transaction count
    - generated timestamp
    - workflow tracking metadata
    """
    workflow = start_workflow_run(
        workflow_name="generate_daily_ops_report",
        triggered_by_role=triggered_by_role,
        summary=f"Started daily operations report for {date}."
    )

    workflow_id = workflow["workflow_id"]

    try:
        report_id = generate_report_id()
        generated_at = datetime.now(timezone.utc).isoformat()

        transaction_summary = get_transaction_summary(date)
        failed_transactions = get_failed_transactions(date)
        failed_count = len(failed_transactions)

        report = {
            "report_id": report_id,
            "workflow_id": workflow_id,
            "report_type": "daily_operations_report",
            "date": date,
            "generated_at": generated_at,
            "generated_by_role": triggered_by_role,
            "transaction_summary": transaction_summary,
            "failed_transaction_count": failed_count,
            "failed_transactions": failed_transactions,
            "notes": [
                "This report was generated by the BankOps MCP workflow system.",
                "The LLM does not directly query the database; it triggers a predefined MCP workflow."
            ]
        }

        REPORTS_DIR.mkdir(exist_ok=True)

        file_name = f"daily_ops_report_{date}_{report_id}.json"
        report_path = REPORTS_DIR / file_name

        with open(report_path, "w", encoding="utf-8") as file:
            json.dump(report, file, indent=2)

        complete_workflow_run(
            workflow_id=workflow_id,
            summary=(
                f"Daily operations report generated for {date}. "
                f"Failed transactions: {failed_count}."
            )
        )

        return {
            "workflow_id": workflow_id,
            "report_id": report_id,
            "date": date,
            "total_failed": failed_count,
            "report_path": str(report_path)
        }

    except Exception as error:
        fail_workflow_run(
            workflow_id=workflow_id,
            summary=f"Failed to generate daily operations report: {str(error)}"
        )

        raise